In [10]:
import sys
import time
from pathlib import Path
from datetime import datetime, timezone
import pandas as pd
from sqlalchemy import text

# Add src to path
sys.path.insert(0, str(Path.cwd().parent.parent / "src"))

from cryptoquant.database.session import get_session
from cryptoquant.config.settings import get_settings


def run_query_with_retry(query, columns, max_retries=3, retry_delay_seconds=15):
    """Execute a query with a fresh session and simple retry handling."""
    for attempt in range(1, max_retries + 1):
        session = None
        try:
            session = get_session()
            rows = session.execute(query).fetchall()
            return pd.DataFrame(rows, columns=columns)
        except Exception:
            if attempt >= max_retries:
                raise
            time.sleep(retry_delay_seconds)
        finally:
            if session is not None:
                session.close()


print("✓ Imports successful")
print(f"Current time: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S')} UTC")

✓ Imports successful
Current time: 2026-09-19 22:57:58 UTC

In [11]:
settings = get_settings()
print(f"✓ Ready to connect to: {settings.database_url}")

✓ Ready to connect to: mssql+pyodbc://fin-admin:S%40123ever%24%23@fin-market-sqlserver.database.windows.net:1433/fin-market-db?driver=ODBC+Driver+18+for+SQL+Server

In [12]:
# Detect market_prices without technical_analysis (after warmup period)
query = text("""
WITH warmup_threshold AS (
    SELECT
        tp.id AS trading_pair_id,
        tp.symbol,
        MIN(mp.timestamp) AS first_candle,
        DATEADD(HOUR, 200, MIN(mp.timestamp)) AS warmup_complete
    FROM crypto.market_prices AS mp
    INNER JOIN crypto.trading_pairs AS tp ON tp.id = mp.trading_pair_id
    GROUP BY tp.id, tp.symbol
)
SELECT
    tp.symbol AS currency_pair,
    mp.id AS market_price_id,
    mp.timestamp,
    mp.[close] AS price
FROM crypto.market_prices AS mp
INNER JOIN crypto.trading_pairs AS tp ON tp.id = mp.trading_pair_id
INNER JOIN warmup_threshold AS w ON w.trading_pair_id = tp.id
LEFT JOIN crypto.technical_analysis AS ta ON ta.market_price_id = mp.id
WHERE mp.timestamp >= w.warmup_complete
  AND ta.id IS NULL
ORDER BY tp.symbol, mp.timestamp
""")

df_missing = run_query_with_retry(
    query,
    ['currency_pair', 'market_price_id', 'timestamp', 'price'],
)

print(f"=== Detected {len(df_missing)} Missing Analysis Record(s) ===")
if len(df_missing) > 0:
    display(df_missing.head(20))
    if len(df_missing) > 20:
        print(f"\n... and {len(df_missing) - 20} more records")
else:
    print("\n✓ No missing analysis detected!")

=== Detected 70693 Missing Analysis Record(s) ===

   currency_pair  market_price_id           timestamp           price
0        BTC-USD             1108 2023-09-01 13:00:00  25990.90000000
1        BTC-USD             1109 2023-09-01 14:00:00  25706.08000000
2        BTC-USD             1110 2023-09-01 15:00:00  25795.09000000
3        BTC-USD             1111 2023-09-01 16:00:00  25765.43000000
4        BTC-USD             1112 2023-09-01 17:00:00  25445.05000000
5        BTC-USD             1113 2023-09-01 18:00:00  25628.10000000
6        BTC-USD             1114 2023-09-01 19:00:00  25628.58000000
7        BTC-USD             1115 2023-09-01 20:00:00  25753.29000000
8        BTC-USD             1116 2023-09-01 21:00:00  25791.94000000
9        BTC-USD             1117 2023-09-01 22:00:00  25754.65000000
10       BTC-USD             1118 2023-09-01 23:00:00  25794.88000000
11       BTC-USD             1119 2023-09-02 00:00:00  25781.77000000
12       BTC-USD             1120 2023-09-02 01:00:00  25768.13000000
13       BTC-USD             1121 2023-09-02 02:00:00  25748.32000000
14       BTC-USD             1122 2023-09-02 03:00:00  25784.80000000
15       BTC-USD             1123 2023-09-02 04:00:00  25766.49000000
16       BTC-USD             1124 2023-09-02 05:00:00  25809.42000000
17       BTC-USD             1125 2023-09-02 06:00:00  25792.98000000
18       BTC-USD             1126 2023-09-02 07:00:00  25787.27000000
19       BTC-USD             1127 2023-09-02 08:00:00  25776.10000000

... and 70673 more records

In [13]:
# Summary by pair with date ranges
if len(df_missing) > 0:
    summary = df_missing.groupby('currency_pair').agg({
        'market_price_id': 'count',
        'timestamp': ['min', 'max']
    })
    summary.columns = ['missing_count', 'first_missing', 'last_missing']
    summary = summary.sort_values('missing_count', ascending=False)
    
    print("\n=== Missing Analysis Summary by Pair ===")
    display(summary)

=== Missing Analysis Summary by Pair ===

               missing_count       first_missing        last_missing
currency_pair
BTC-USD                25948 2023-09-01 13:00:00 2026-08-18 02:00:00
ETH-USD                17497 2024-09-02 11:00:00 2026-09-01 21:00:00
SOL-USD                17350 2024-09-08 14:00:00 2026-09-01 21:00:00
XRP-USD                 9898 2025-07-16 02:00:00 2026-09-01 21:00:00

In [14]:
# Detect contiguous missing analysis gaps from the same definition used above
if len(df_missing) > 0:
    query = text("""
    WITH warmup_threshold AS (
        SELECT
            tp.id AS trading_pair_id,
            tp.symbol,
            DATEADD(HOUR, 200, MIN(mp.timestamp)) AS warmup_complete
        FROM crypto.market_prices AS mp
        INNER JOIN crypto.trading_pairs AS tp ON tp.id = mp.trading_pair_id
        GROUP BY tp.id, tp.symbol
    ),
    missing_rows AS (
        SELECT
            tp.symbol AS currency_pair,
            mp.timestamp
        FROM crypto.market_prices AS mp
        INNER JOIN crypto.trading_pairs AS tp ON tp.id = mp.trading_pair_id
        INNER JOIN warmup_threshold AS w ON w.trading_pair_id = tp.id
        LEFT JOIN crypto.technical_analysis AS ta ON ta.market_price_id = mp.id
        WHERE mp.timestamp >= w.warmup_complete
          AND ta.id IS NULL
    ),
    grouped_missing AS (
        SELECT
            currency_pair,
            timestamp,
            DATEADD(HOUR, -ROW_NUMBER() OVER (PARTITION BY currency_pair ORDER BY timestamp), timestamp) AS gap_group
        FROM missing_rows
    )
    SELECT
        currency_pair,
        MIN(timestamp) AS gap_start,
        MAX(timestamp) AS gap_end,
        COUNT(*) AS missing_hours
    FROM grouped_missing
    GROUP BY currency_pair, gap_group
    ORDER BY currency_pair, gap_start
    """)

    df_analysis_gaps = run_query_with_retry(
        query,
        ['currency_pair', 'gap_start', 'gap_end', 'missing_hours'],
    )
else:
    df_analysis_gaps = pd.DataFrame(columns=['currency_pair', 'gap_start', 'gap_end', 'missing_hours'])

print(f"\n=== Detected {len(df_analysis_gaps)} Contiguous Analysis Gap Range(s) ===")
if len(df_analysis_gaps) > 0:
    display(df_analysis_gaps.head(50))
    if len(df_analysis_gaps) > 50:
        print(f"\n... and {len(df_analysis_gaps) - 50} more gap ranges")
    total_missing_hours = int(df_analysis_gaps['missing_hours'].sum())
    print(f"\n⚠️  Total missing analysis hours: {total_missing_hours:,.0f}")
else:
    print("✓ No missing analysis gaps detected!")

=== Detected 12 Contiguous Analysis Gap Range(s) ===

   currency_pair           gap_start             gap_end  missing_hours
0        BTC-USD 2023-09-01 13:00:00 2025-10-25 15:00:00          18843
1        BTC-USD 2025-10-25 21:00:00 2026-05-08 01:00:00           4661
2        BTC-USD 2026-05-08 07:00:00 2026-08-18 02:00:00           2444
3        ETH-USD 2024-09-02 11:00:00 2025-10-25 15:00:00          10037
4        ETH-USD 2025-10-25 21:00:00 2026-05-08 01:00:00           4661
5        ETH-USD 2026-05-08 07:00:00 2026-09-01 21:00:00           2799
6        SOL-USD 2024-09-08 14:00:00 2025-10-25 15:00:00           9890
7        SOL-USD 2025-10-25 21:00:00 2026-05-08 01:00:00           4661
8        SOL-USD 2026-05-08 07:00:00 2026-09-01 21:00:00           2799
9        XRP-USD 2025-07-16 02:00:00 2025-10-25 15:00:00           2438
10       XRP-USD 2025-10-25 21:00:00 2026-05-08 01:00:00           4661
11       XRP-USD 2026-05-08 07:00:00 2026-09-01 21:00:00           2799

⚠️  Total missing analysis hours: 70,693

In [15]:
# Generate backfill commands
print("\n=== Backfill Commands ===\n")

if len(df_missing) > 0 or len(df_analysis_gaps) > 0:
    print("# Run incremental mode to fill all missing analysis records:")
    print("python scripts/calculate_technical_analysis.py --mode incremental\n")

    if len(df_missing) > 0:
        pair_summary = df_missing.groupby('currency_pair').agg(
            missing_count=('market_price_id', 'count'),
            first_missing=('timestamp', 'min'),
            last_missing=('timestamp', 'max'),
        ).sort_values('missing_count', ascending=False)

        print("# Missing record summary by pair:")
        display(pair_summary)

        print("\n# Optional pair-specific incremental runs:")
        for pair in pair_summary.index:
            print(f"python scripts/calculate_technical_analysis.py --mode incremental --pair {pair}")

    if len(df_analysis_gaps) > 0:
        print("\n# Contiguous gap ranges (first 20):")
        display(df_analysis_gaps.head(20))
else:
    print("✓ No backfill needed - all analysis is complete!")

=== Backfill Commands ===

# Run incremental mode to fill all missing analysis records:
python scripts/calculate_technical_analysis.py --mode incremental

# Missing record summary by pair:

               missing_count       first_missing        last_missing
currency_pair
BTC-USD                25948 2023-09-01 13:00:00 2026-08-18 02:00:00
ETH-USD                17497 2024-09-02 11:00:00 2026-09-01 21:00:00
SOL-USD                17350 2024-09-08 14:00:00 2026-09-01 21:00:00
XRP-USD                 9898 2025-07-16 02:00:00 2026-09-01 21:00:00

# Optional pair-specific incremental runs:
python scripts/calculate_technical_analysis.py --mode incremental --pair BTC-USD
python scripts/calculate_technical_analysis.py --mode incremental --pair ETH-USD
python scripts/calculate_technical_analysis.py --mode incremental --pair SOL-USD
python scripts/calculate_technical_analysis.py --mode incremental --pair XRP-USD

# Contiguous gap ranges (first 20):

   currency_pair           gap_start             gap_end  missing_hours
0        BTC-USD 2023-09-01 13:00:00 2025-10-25 15:00:00          18843
1        BTC-USD 2025-10-25 21:00:00 2026-05-08 01:00:00           4661
2        BTC-USD 2026-05-08 07:00:00 2026-08-18 02:00:00           2444
3        ETH-USD 2024-09-02 11:00:00 2025-10-25 15:00:00          10037
4        ETH-USD 2025-10-25 21:00:00 2026-05-08 01:00:00           4661
5        ETH-USD 2026-05-08 07:00:00 2026-09-01 21:00:00           2799
6        SOL-USD 2024-09-08 14:00:00 2025-10-25 15:00:00           9890
7        SOL-USD 2025-10-25 21:00:00 2026-05-08 01:00:00           4661
8        SOL-USD 2026-05-08 07:00:00 2026-09-01 21:00:00           2799
9        XRP-USD 2025-07-16 02:00:00 2025-10-25 15:00:00           2438
10       XRP-USD 2025-10-25 21:00:00 2026-05-08 01:00:00           4661
11       XRP-USD 2026-05-08 07:00:00 2026-09-01 21:00:00           2799

In [16]:
# Run backfill directly from the notebook when gaps are detected
import subprocess

RUN_BACKFILL = False  # Set to True when you want to execute backfill from this notebook
BACKFILL_MODE = "incremental"
RUN_PER_PAIR = True
BACKFILL_PAIR = None  # Example: "BTC-USD" to force a single pair
MAX_RETRIES = 3
RETRY_DELAY_SECONDS = 30

project_root = Path.cwd().parent.parent
script_path = project_root / "scripts" / "calculate_technical_analysis.py"

if not script_path.exists():
    raise FileNotFoundError(f"Backfill script not found: {script_path}")


def run_backfill_command(cmd):
    """Run one backfill command with retry for transient SQL connectivity errors."""
    last_result = None

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"\nAttempt {attempt}/{MAX_RETRIES}: {' '.join(cmd)}")
        result = subprocess.run(
            cmd,
            cwd=str(project_root),
            capture_output=True,
            text=True,
        )
        last_result = result

        if result.stdout:
            print("\n--- Backfill stdout ---")
            print(result.stdout)

        if result.stderr:
            print("\n--- Backfill stderr ---")
            print(result.stderr)

        if result.returncode == 0:
            return result

        stderr_text = (result.stderr or "").lower()
        is_transient_connectivity_error = (
            "login timeout expired" in stderr_text
            or "tcp provider: timeout" in stderr_text
            or "connection is busy" in stderr_text
        )

        if not is_transient_connectivity_error or attempt == MAX_RETRIES:
            break

        print(f"Transient database connectivity issue detected. Retrying in {RETRY_DELAY_SECONDS}s...")
        time.sleep(RETRY_DELAY_SECONDS)

    return last_result


if len(df_missing) == 0:
    print("✓ No missing analysis records found. Backfill is not required.")
elif not RUN_BACKFILL:
    print("Backfill is configured in this notebook and currently disabled.")
    print("Set RUN_BACKFILL = True to execute.")
else:
    commands = []

    if BACKFILL_PAIR:
        commands.append([sys.executable, str(script_path), "--mode", BACKFILL_MODE, "--pair", BACKFILL_PAIR])
    elif RUN_PER_PAIR:
        pairs = sorted(df_missing['currency_pair'].unique())
        for pair in pairs:
            commands.append([sys.executable, str(script_path), "--mode", BACKFILL_MODE, "--pair", pair])
    else:
        commands.append([sys.executable, str(script_path), "--mode", BACKFILL_MODE])

    print("=== Running Backfill ===")
    print(f"Commands to run: {len(commands)}")

    failed_commands = []

    for idx, cmd in enumerate(commands, start=1):
        print(f"\n[{idx}/{len(commands)}] Command: {' '.join(cmd)}")
        result = run_backfill_command(cmd)

        if result.returncode != 0:
            failed_commands.append((cmd, result.returncode))

    if failed_commands:
        print("\n=== Backfill completed with failures ===")
        for cmd, code in failed_commands:
            print(f"Exit {code}: {' '.join(cmd)}")
        raise RuntimeError(f"Backfill failed for {len(failed_commands)} command(s)")

    print("\n✓ Backfill completed successfully")

Backfill is configured in this notebook and currently disabled.
Set RUN_BACKFILL = True to execute.

In [17]:
print("✓ Notebook complete")

✓ Notebook complete